### ISSUE TITLE
Chapter 2, example listing 2.1, $ is not defined

### ISSUE THREAD

**Issue by leiguoyang** [AurelioDeRosa/jquery-in-action#2]
@AurelioDeRosa Nice to learn from you. 

I meet a problem when running the example *Listing2.1 Using the universal selector with jQuery* in Chapter2, Page28. When I open the console, it says `ReferenceError: $ is not defined`. I run the example offline with Firefox 50.0.

And then I run it online, the same error message occurs. I wonder what's wrong. 😕

**Comment by reiy-leo** [comment]
it means you didn't load the JQuery library

**Comment by leiguoyang** [comment]
@Antisunny Are you also a reader of this book? I agree with you. When I work offline, this code of line 
```javascript
var $allElements = $('*');
```
is executed before the local jQuery library file is created, I think. 

In addition, I wonder why the example fail when I run it online.

**Comment by reiy-leo** [comment]
the jq library should be loaded before any jQuery statements. and the $ is a alias to jQuery object itself. I don't understand what does the online or offline mean. QQ: 1132012451 if any doubt

**Comment by AurelioDeRosa** [comment]
Hi @leiguoyang.

First of all, sorry for the late reply. I hope you're enjoying the book.

I think you're seeing this error because you're opening the file without a web server like Apache. This means that in the address bar you see something like **file:///**. If that's the case, the library will fail to load because the use of the HTTP (or HTTPS) protocol is needed. If you have a website, upload the HTML page and then access it (for example http://www.your-website.com/listing-2.1.html). You'll see that it won't show the error.

An alternative solution is to execute the file inside the folder where it was stored (for example if you have downloaded the code from [the Manning website](https://www.manning.com/books/jquery-in-action-third-edition)). By doing so, the page will search for the version of jQuery I've included with the code.

I hope this helps.

**Comment by leiguoyang** [comment]
@AurelioDeRosa Thank you. I upload the `listing-2.1.html` file to my website and no error shown on the console.

**Comment by AurelioDeRosa** [comment]
I'm glad I was helpful.
